/// Generated by AssetsRefGenerator on 2021/06/04
class Res {
  static const String add_user = "assets/image/add_user.png";
  static const String arrow_down = "assets/image/arrow_down.png";
  static const String back = "assets/image/back.png";
  static const String checked_box = "assets/image/checked_box.png";
  static const String email = "assets/image/email.png";
  static const String mobile = "assets/image/mobile.png";
  static const String password = "assets/image/password.png";
  static const String user = "assets/image/user.png";
}
